[[pages]]
path = "DocuMentor.py"



[[pages]]
path = "1_Ask_Question.py"
name = "Ask Question"
icon = "💬"



[[pages]]
path = "03_Compare_Your_PDF_FAISS.py"
name = "Compare Your Documents"
icon = "📖"
