[[pages]]
path = "Home.py"
name = "DocuMentor"


[[pages]]
path = "pages/1_Ask_Question.py"
name = "Ask_Question"
icon = ":books:"



[[pages]]
path = "pages/03_Compare_Your_PDF_FAISS.py"
name = "Compare_Your_PDFs"
icon = "📖"
